encyclopedia/urls.py
from django.urls import path

from . import views

app_name="encl"

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:name>",views.MtoH, name="mtoh"),
    path("new", views.New, name="New"),
    path("wiki/<str:name>/edite", views.edite, name="edite"),
    path("random", views.random1, name="random"),
    path("wiki/<str:name>/delete", views.delete, name="delete"),
]

wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name="encl"

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:name>",views.MtoH, name="mtoh"),
    path("new", views.New, name="New"),
    path("wiki/<str:name>/edite", views.edite, name="edite"),
    path("random", views.random1, name="random")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/forms.py
from django import forms

class searchform(forms.Form):
    search = forms.CharField(label="")

class addform(forms.Form):
    title = forms.CharField(label="title")
    content = forms.CharField(widget = forms.Textarea)

class editeform(forms.Form):
    title = forms.CharField(label="title")
    content = forms.CharField(widget = forms.Textarea)

encyclopedia/views.py
import os
from calendar import timegm
from tkinter.font import nametofont
from django.shortcuts import render,redirect
from . import util
import markdown
from .forms import addform
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.urls import reverse
import random

def change(name):
    if util.get_entry(name):
        return  markdown.markdown(util.get_entry(name))
    else : 
        name = 'Error'
        return markdown.markdown(util.get_entry(name))

def index(request):
    entrys = util.list_entries()
    if request.method == "POST":
        cd = request.POST['q']
        entrys = filter(lambda x : x.upper().find(cd.upper())!=-1 ,entrys)
    return render(request, "encyclopedia/index.html", {
        "entries": entrys, 
    })
    

def MtoH(request, name):
    entrys = util.list_entries()
    context={
        "html":change(name),  "name":name, "entries":entrys
    }
    return render(request, "encyclopedia/details.html",context)

def New(request):
    if request.method == "POST":
        form = addform(request.POST)
        if form.is_valid():
            titles = form.cleaned_data["title"]
            contents = form.cleaned_data["content"]
            if util.get_entry(titles):
                return render(request, "encyclopedia/new.html",{
                    "new": form,
                    "Error": "* This page is already exist",
                })
            util.save_entry(titles, contents)
            messages.success(request, 'New page Added Successfully')
            return HttpResponseRedirect(reverse("encl:mtoh", args=(titles,)))
    return render(request, "encyclopedia/new.html",{
        "new": addform()
    })

def edite(request,name):
    if request.method == "POST":
        textarea = request.POST['textarea']
        util.save_entry(name, textarea)
        messages.success(request, 'Changes Saved!')
        return HttpResponseRedirect(reverse("encl:mtoh", args=(name,)))
    
    context={
        "head": name,
        "body": util.get_entry(name),
    }
    return render(request, "encyclopedia/edite.html",context)

def delete (request, name):
    util.delete_entry(name)
    messages.success(request, 'Content Deleted!')
    return redirect("encl:index")
    

def random1(request):
    entries = util.list_entries()
    name = random.choice(entries)
    return HttpResponseRedirect(reverse("encl:mtoh", args=(name,)))

wiki/encyclopedia/views.py
from calendar import timegm
from tkinter.font import nametofont
from django.shortcuts import render
from . import util
import markdown
from .forms import searchform
from .forms import addform
from .forms import editeform
from django.http import HttpResponseRedirect
from django.urls import reverse
import random

def change(name):
    if util.get_entry(name):
        return  markdown.markdown(util.get_entry(name))
    else : 
        name = 'Error'
        return markdown.markdown(util.get_entry(name))

def index(request):
    entrys = util.list_entries()
    if request.method == "POST":
        cd = request.POST['q']
        entrys = filter(lambda x : x.upper().find(cd.upper())!=-1 ,entrys)
    return render(request, "encyclopedia/index.html", {
        "entries": entrys, 
    })
    

def MtoH(request, name):
    entrys = util.list_entries()
    context={
        "html":change(name),  "name":name, "entries":entrys
    }
    return render(request, "encyclopedia/mult.html",context)

def New(request):
    if request.method == "POST":
        form = addform(request.POST)
        if form.is_valid():
            titles = form.cleaned_data["title"]
            contents = form.cleaned_data["content"]
            if util.get_entry(titles):
                return render(request, "encyclopedia/new.html",{
                    "new": form,
                    "Error": "* This page is already exist",
                })
            util.save_entry(titles, contents)
            return HttpResponseRedirect(reverse("encl:mtoh", args=(titles,)))
    return render(request, "encyclopedia/new.html",{
        "new": addform()
    })

def edite(request,name):
    if request.method == "POST":
        textarea = request.POST['textarea']
        util.save_entry(name, textarea)
        return HttpResponseRedirect(reverse("encl:mtoh", args=(name,)))
    context={
        "head": name,
        "body": util.get_entry(name),
    }
    return render(request, "encyclopedia/edite.html",context)

def random1(request):
    entries = util.list_entries()
    name = random.choice(entries)
    return HttpResponseRedirect(reverse("encl:mtoh", args=(name,)))

encyclopedia/templates/encyclopedia/details.html
{% extends "encyclopedia/layout.html" %}
{% block css %}
<style>
    .delete{
            
        padding-left:15px;
        padding-right:15px;
        padding-bottom:2px;
        border-radius:5px;
        background-color:red;
        color: white;
        border:None;
        position:relative;
        top:79px;
    }
    .a{
            
    padding-left:15px;
    padding-right:15px;
    padding-bottom:2px;
    border-radius:5px;
    background-color: #007bff;
    color: white;
    border:None;
    position:relative;
    top:79px;
    }
</style>
{% endblock css %}
{% block title %}
    {{name}}
{% endblock title%}



{% block body %}
    {% if name not in entries %}
        {{html|safe}}
    {% else %}
        {{html|safe}}
        <a href="{{ name }}/edite"class="a"> Edite Page</a>
        <a href="{{name}}/delete" class="delete" >Delete Page</a>
    {% endif %}
{% endblock %}

encyclopedia/templates/encyclopedia/edite.html
{% extends "encyclopedia/layout.html" %}
{% load widget_tweaks %}

{% block css %}
    <style>

        .content{
            width:600px;
            height:400px;
            position:relative;
            top:0px;
            right:0px;
            left:10px;
            border-radius:8px;
            border:thin solid rgb(199, 199, 199);
            
        }
        h1{
            position:relative;
            left:0px;
            padding:10px;
        }
        .content:hover{
            box-shadow: 1px 1px 3px 0px rgb(201, 201, 201);
        }
        .content:focus{
            outline:0;
            box-shadow: 1px 1px 3px 0px rgb(201, 201, 201);
        }
        p{
            font-size :20px ;
            
            position:relative;
            left:12px;
            bottom:3px;
            font-weight: bolder;
        }
        .button{
            
            padding-left:15px;
            padding-right:15px;
            padding-bottom:2px;
            border-radius:5px;
            background-color:#007bff;
            color: white;
            border:None;
            position:relative;
            right:95px;
            top:30px;
        }
        
        .button:hover{
            box-shadow: 2px 3px 3px 0px rgb(201, 201, 201);
        }


    </style>
{% endblock %}

{% block title %}
    Edite Page
{% endblock %}

{% block body %}
    <h1>Edit Existed Page</h1>

   <form action="" method="post">
        {% csrf_token %}
        <p>Title : {{ head }}</p>
        <textarea name="textarea" class="content">{{body}}</textarea>
        <button type="submit" class="button" >Save Page</button>
        
   </form>
   <p>{{Error}}</p>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href = "/wiki/{{ entry }}">{{ entry }}</a></li>
            {% empty %}
                <p>Nothing Found</p>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}


<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
        {% block css %}{% endblock %}
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                {% if messages %}
                    {% for msg in messages %}
                        <p class="alert alert-success"> {{msg}} </p>
                    {% endfor %}
                {% endif %}
                <form class="search" action="" method="post">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encl:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encl:New' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encl:random' %}" name="random" method="post">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/mult.html
{% extends "encyclopedia/layout.html" %}
{% block css %}
<style>
    .delete{
            
        padding-left:15px;
        padding-right:15px;
        padding-bottom:2px;
        border-radius:5px;
        background-color:red;
        color: white;
        border:None;
        position:relative;
        {% comment %} right:335px; {% endcomment %}
        top:79px;
    }
    .a{
            
    padding-left:15px;
    padding-right:15px;
    padding-bottom:2px;
    border-radius:5px;
    background-color: #007bff;
    color: white;
    border:None;
    position:relative;
    {% comment %} right:286px; {% endcomment %}
    top:79px;
    }
</style>
{% endblock css %}
{% block title %}
    {{name}}
{% endblock title%}



{% block body %}
    {% if name not in entries %}
        {{html|safe}}
    {% else %}
        {{html|safe}}
        <a href="{{ name }}/edite"class="a"> Edite Page</a>
        <a href="{{name}}/delete" class="delete" >Delete Page</a>
    {% endif %}
{% endblock %}

encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}
{% load widget_tweaks %}

{% block css %}
    <style>

        .content{
            width:600px;
            height:400px;
            position:relative;
            top:50px;
            right:180px;
            border-radius:8px;
            border:thin solid rgb(199, 199, 199);
            
        }
        .title{
            position:relative;
            bottom:370px;
            left:13px;
            margin-bottom:10px;
            border-radius:6px;
            border:thin solid rgb(199, 199, 199);
            
        }
        h1{
            position:relative;
            left:4px;
            padding:10px;
        }
        .content:hover{
            box-shadow: 1px 1px 3px 0px rgb(201, 201, 201);
        }
        .title:hover{
            box-shadow: 1px 1px 3px 0px rgb(201, 201, 201);
        }
        .content:focus{
            outline:0;
            box-shadow: 1px 1px 3px 0px rgb(201, 201, 201);
        }
        .title:focus{
            outline:0;
            box-shadow: 0px 0px 3px 0px rgb(177, 174, 174);
        }
        p{
            position:relative;
            top : 50px;
            left : 15px;
            color: red;
            size : 15px;
        }

        .button{
            
            padding-left:15px;
            padding-right:15px;
            padding-bottom:2px;
            border-radius:5px;
            background-color: #007bff;
            color: white;
            border:None;
            position:relative;
            right:286px;
            top:79px;
        }
        .button:hover{
            box-shadow: 2px 3px 3px 0px rgb(201, 201, 201);
        }

    </style>
{% endblock %}

{% block title %}
    Create New Page
{% endblock %}

{% block body %}
    <h1>Create New Page</h1>

   <form action="" method="post">
        {% csrf_token %}
        {% render_field new.title type="text" class="title"  placeholder="Title" %}
        {% render_field new.content type="text" class="content" placeholder="Content" %}
        <button type="submit" class="button">Save Page</button>
        
   </form>
   <p>{{Error}}</p>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/edite.html
{% extends "encyclopedia/layout.html" %}
{% load widget_tweaks %}

{% block css %}
    <style>

        .content{
            width:600px;
            height:400px;
            position:relative;
            top:0px;
            right:0px;
            left:10px;
            border-radius:8px;
            border:thin solid rgb(199, 199, 199);
            
        }
        h1{
            position:relative;
            left:0px;
            padding:10px;
        }
        .content:hover{
            box-shadow: 1px 1px 3px 0px rgb(201, 201, 201);
        }
        .content:focus{
            outline:0;
            box-shadow: 1px 1px 3px 0px rgb(201, 201, 201);
        }
        p{
            font-size :20px ;
            
            position:relative;
            left:12px;
            bottom:3px;
            font-weight: bolder;
        }
        .button{
            
            padding-left:15px;
            padding-right:15px;
            padding-bottom:2px;
            border-radius:5px;
            background-color: #007bff;
            color: white;
            border:None;
            position:relative;
            right:95px;
            top:30px;
        }
        .button:hover{
            box-shadow: 2px 3px 3px 0px rgb(201, 201, 201);
        }


    </style>
{% endblock %}

{% block title %}
    Edite Page
{% endblock %}

{% block body %}
    <h1>Create New Page</h1>

   <form action="" method="post">
        {% csrf_token %}
        <p>Title : {{ head }}</p>
        <textarea name="textarea" class="content">{{body}}</textarea>
        <button type="submit" class="button" >Save Page</button>
   </form>
   <p>{{Error}}</p>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}


<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
        {% block css %}{% endblock %}
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form class="search" action="" method="post">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encl:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encl:New' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encl:random' %}" name="random" method="post">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/mult.html
{% extends "encyclopedia/layout.html" %}
{% block css %}
.button{
            
    padding-left:15px;
    padding-right:15px;
    padding-bottom:2px;
    border-radius:5px;
    background-color: #007bff;
    color: white;
    border:None;
    position:relative;
    right:286px;
    top:79px;
}
{% endblock css %}
{% block title %}
    {{name}}
{% endblock title%}



{% block body %}
    {% if name not in entries %}
        {{html|safe}}
    {% else %}
        {{html | safe}}
        <a href="{{ name }}/edite"><p class="button"> Edite Page</p></a>
    {% endif %}
{% endblock %}